# 公用配置
spring:
  profiles:
    # maven在build的时候会自动替换，手动写死的话容易忘记
    active: @springboot.active-environment@
  jackson:
    # 序列化时，驼峰命名转为下划线命名
    property-naming-strategy: SNAKE_CASE
    # 日期序列化配置
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# 开启mybatis驼峰下划线自动转换
mybatis:
  configuration:
    map-underscore-to-camel-case: true



# MySQL中有谜语题库有多少道题
riddle:
  total-number: 600

match-interface:
  # match的时候间隔多长时间进行一次匹配（单位：毫秒）
  match-interval: 10000
  # match接口从什么时间到什么时间开放
  time-format: yyyy-MM-dd HH:mm:ss
  #  open-time: "2021-02-27 18:00:00"
  #  close-time: "2021-02-27 21:00:00"
  open-time: "2021-02-13 9:00:00"
  close-time: "2021-02-19 9:00:00"
